# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-03 14:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=50)),
                ('town', models.CharField(max_length=50)),
                ('village', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Option_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parking', models.BooleanField(default=False)),
                ('elevator', models.BooleanField(default=False)),
                ('animal', models.BooleanField(default=False)),
                ('aricon', models.BooleanField(default=False)),
                ('washer', models.BooleanField(default=False)),
                ('freezer', models.BooleanField(default=False)),
                ('tv', models.BooleanField(default=False)),
                ('doorlock', models.BooleanField(default=False)),
                ('bed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Room_info',
            fields=[
                ('rome_num', models.AutoField(primary_key=True, serialize=False)),
                ('owner_pho_num', models.CharField(max_length=50)),
                ('deposit', models.IntegerField()),
                ('monthly', models.IntegerField()),
                ('manage_money', models.IntegerField()),
                ('rome_name', models.CharField(max_length=50)),
                ('rome_area', models.IntegerField()),
                ('total_floor', models.IntegerField()),
                ('rome_floor', models.IntegerField()),
                ('detail_address', models.CharField(max_length=50)),
                ('create_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-create_date'],
            },
        ),
        migrations.AddField(
            model_name='option_info',
            name='rome_num',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jejudaum.Room_info'),
        ),
        migrations.AddField(
            model_name='address',
            name='rome_num',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jejudaum.Room_info'),
        ),
    ]
